## Customize the test machine
general:
  build_dir: php-dark-launch
machine:
  php:
    version: 5.5.21
    
## Customize dependencies
dependencies:
  pre:
    - pecl install redis
    - composer install

## Customize test commands
test:
  override:
    - ./vendor/behat/behat/bin/behat
